runtime: nodejs10

env_variables:
  DB_USER: root
  DB_PASS: a0937838260
  DB_NAME: space_shooter
  CLOUD_SQL_CONNECTION_NAME: sqllearn-276509:asia-east2:mysql-space-shooter

beta_settings:
  cloud_sql_instances: sqllearn-276509:asia-east2:mysql-space-shooter